import 'package:flutter/material.dart';

void main() {
  runApp(myApp());
}

class myApp extends StatelessWidget {
  const myApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text("LUDU GAME", style: TextStyle(color: Colors.white)),
          backgroundColor: Colors.amber,
        ),
        body: Column(
          children: [
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.red),
                Container(height: 50, width: 50, color: Colors.white),
                Container(height: 50, width: 50, color: Colors.white),
                Container(height: 50, width: 50, color: Colors.white),
                Container(height: 50, width: 50, color: Colors.green),
                Container(height: 50, width: 50, color: Colors.green),
                Container(height: 50, width: 50, color: Colors.green),
                Container(height: 50, width: 50, color: Colors.green),
                Container(height: 50, width: 50, color: Colors.green),
                Container(height: 50, width: 50, color: Colors.green),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
            Row(
              children: [
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
                Container(height: 50, width: 50, color: Colors.blue),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
