import 'package:flutter/material.dart';

void main() {
  runApp(myApp());
}

class myApp extends StatelessWidget {
  const myApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        appBar: AppBar(
          title: Text("LUDU GAME", style: TextStyle(color: Colors.white)),
          backgroundColor: Colors.amber,
        ),
        body: Column(
          children: [
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.green,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.red,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.purpleAccent,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
            Row(
              children: [
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.blue,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.white,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
                Container(height: 35, width: 35,decoration: BoxDecoration(color: Colors.yellow,border: Border.all(color: Colors.black, width: 1))),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
